- name: check a nuber is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: number < 10

  - name: print this if grether than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is grether than or equal to 10"
    when: number => 10      