- name: check a nuber is less than 10 or not
  hosts: local
  connection: local
    vars:
      my_number = 100
  # vars_prompt:
  # - name: my_number
  #   prompt: please enter the number
  #   private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int < 10

  - name: print this if grether than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is grether than or equal to 10"
    when: my_number | int => 10     